//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.CalcService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://websrv.cs.fsu.edu/~engelen/calc.wsdl", ConfigurationName="CalcService.calcPortType")]
    public interface calcPortType {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ przestrzeń nazw otoki (urn:calc) komunikatu addRequest nie pasuje do domyślnej wartości (http://websrv.cs.fsu.edu/~engelen/calc.wsdl).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.CalcService.addResponse add(WebApplication1.CalcService.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.CalcService.addResponse> addAsync(WebApplication1.CalcService.addRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ przestrzeń nazw otoki (urn:calc) komunikatu subRequest nie pasuje do domyślnej wartości (http://websrv.cs.fsu.edu/~engelen/calc.wsdl).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.CalcService.subResponse sub(WebApplication1.CalcService.subRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.CalcService.subResponse> subAsync(WebApplication1.CalcService.subRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ przestrzeń nazw otoki (urn:calc) komunikatu mulRequest nie pasuje do domyślnej wartości (http://websrv.cs.fsu.edu/~engelen/calc.wsdl).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.CalcService.mulResponse mul(WebApplication1.CalcService.mulRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.CalcService.mulResponse> mulAsync(WebApplication1.CalcService.mulRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ przestrzeń nazw otoki (urn:calc) komunikatu divRequest nie pasuje do domyślnej wartości (http://websrv.cs.fsu.edu/~engelen/calc.wsdl).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.CalcService.divResponse div(WebApplication1.CalcService.divRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.CalcService.divResponse> divAsync(WebApplication1.CalcService.divRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ przestrzeń nazw otoki (urn:calc) komunikatu powRequest nie pasuje do domyślnej wartości (http://websrv.cs.fsu.edu/~engelen/calc.wsdl).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.CalcService.powResponse pow(WebApplication1.CalcService.powRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.CalcService.powResponse> powAsync(WebApplication1.CalcService.powRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public addRequest() {
        }
        
        public addRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public addResponse() {
        }
        
        public addResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sub", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class subRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public subRequest() {
        }
        
        public subRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class subResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public subResponse() {
        }
        
        public subResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mul", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class mulRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public mulRequest() {
        }
        
        public mulRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mulResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class mulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public mulResponse() {
        }
        
        public mulResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class divRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public divRequest() {
        }
        
        public divRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class divResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public divResponse() {
        }
        
        public divResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pow", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class powRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public powRequest() {
        }
        
        public powRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="powResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class powResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public powResponse() {
        }
        
        public powResponse(double result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calcPortTypeChannel : WebApplication1.CalcService.calcPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calcPortTypeClient : System.ServiceModel.ClientBase<WebApplication1.CalcService.calcPortType>, WebApplication1.CalcService.calcPortType {
        
        public calcPortTypeClient() {
        }
        
        public calcPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calcPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calcPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calcPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.CalcService.addResponse WebApplication1.CalcService.calcPortType.add(WebApplication1.CalcService.addRequest request) {
            return base.Channel.add(request);
        }
        
        public double add(double a, double b) {
            WebApplication1.CalcService.addRequest inValue = new WebApplication1.CalcService.addRequest();
            inValue.a = a;
            inValue.b = b;
            WebApplication1.CalcService.addResponse retVal = ((WebApplication1.CalcService.calcPortType)(this)).add(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.CalcService.addResponse> WebApplication1.CalcService.calcPortType.addAsync(WebApplication1.CalcService.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.CalcService.addResponse> addAsync(double a, double b) {
            WebApplication1.CalcService.addRequest inValue = new WebApplication1.CalcService.addRequest();
            inValue.a = a;
            inValue.b = b;
            return ((WebApplication1.CalcService.calcPortType)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.CalcService.subResponse WebApplication1.CalcService.calcPortType.sub(WebApplication1.CalcService.subRequest request) {
            return base.Channel.sub(request);
        }
        
        public double sub(double a, double b) {
            WebApplication1.CalcService.subRequest inValue = new WebApplication1.CalcService.subRequest();
            inValue.a = a;
            inValue.b = b;
            WebApplication1.CalcService.subResponse retVal = ((WebApplication1.CalcService.calcPortType)(this)).sub(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.CalcService.subResponse> WebApplication1.CalcService.calcPortType.subAsync(WebApplication1.CalcService.subRequest request) {
            return base.Channel.subAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.CalcService.subResponse> subAsync(double a, double b) {
            WebApplication1.CalcService.subRequest inValue = new WebApplication1.CalcService.subRequest();
            inValue.a = a;
            inValue.b = b;
            return ((WebApplication1.CalcService.calcPortType)(this)).subAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.CalcService.mulResponse WebApplication1.CalcService.calcPortType.mul(WebApplication1.CalcService.mulRequest request) {
            return base.Channel.mul(request);
        }
        
        public double mul(double a, double b) {
            WebApplication1.CalcService.mulRequest inValue = new WebApplication1.CalcService.mulRequest();
            inValue.a = a;
            inValue.b = b;
            WebApplication1.CalcService.mulResponse retVal = ((WebApplication1.CalcService.calcPortType)(this)).mul(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.CalcService.mulResponse> WebApplication1.CalcService.calcPortType.mulAsync(WebApplication1.CalcService.mulRequest request) {
            return base.Channel.mulAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.CalcService.mulResponse> mulAsync(double a, double b) {
            WebApplication1.CalcService.mulRequest inValue = new WebApplication1.CalcService.mulRequest();
            inValue.a = a;
            inValue.b = b;
            return ((WebApplication1.CalcService.calcPortType)(this)).mulAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.CalcService.divResponse WebApplication1.CalcService.calcPortType.div(WebApplication1.CalcService.divRequest request) {
            return base.Channel.div(request);
        }
        
        public double div(double a, double b) {
            WebApplication1.CalcService.divRequest inValue = new WebApplication1.CalcService.divRequest();
            inValue.a = a;
            inValue.b = b;
            WebApplication1.CalcService.divResponse retVal = ((WebApplication1.CalcService.calcPortType)(this)).div(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.CalcService.divResponse> WebApplication1.CalcService.calcPortType.divAsync(WebApplication1.CalcService.divRequest request) {
            return base.Channel.divAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.CalcService.divResponse> divAsync(double a, double b) {
            WebApplication1.CalcService.divRequest inValue = new WebApplication1.CalcService.divRequest();
            inValue.a = a;
            inValue.b = b;
            return ((WebApplication1.CalcService.calcPortType)(this)).divAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.CalcService.powResponse WebApplication1.CalcService.calcPortType.pow(WebApplication1.CalcService.powRequest request) {
            return base.Channel.pow(request);
        }
        
        public double pow(double a, double b) {
            WebApplication1.CalcService.powRequest inValue = new WebApplication1.CalcService.powRequest();
            inValue.a = a;
            inValue.b = b;
            WebApplication1.CalcService.powResponse retVal = ((WebApplication1.CalcService.calcPortType)(this)).pow(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.CalcService.powResponse> WebApplication1.CalcService.calcPortType.powAsync(WebApplication1.CalcService.powRequest request) {
            return base.Channel.powAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.CalcService.powResponse> powAsync(double a, double b) {
            WebApplication1.CalcService.powRequest inValue = new WebApplication1.CalcService.powRequest();
            inValue.a = a;
            inValue.b = b;
            return ((WebApplication1.CalcService.calcPortType)(this)).powAsync(inValue);
        }
    }
}
